from rest_framework import serializers

class SubmitReviewBinViewInputModel(serializers.Serializer):
    isAdjudicatedInReviewBin = serializers.BooleanField(default=False)
    isSendBackToSubmissionView = serializers.BooleanField(default=False)
    isSendToAgencyAdjucationView = serializers.BooleanField(default=False)
    videoId = serializers.IntegerField(required=False,allow_null=True)
    imageId = serializers.IntegerField(required=False,allow_null=True)
    tattileId = serializers.IntegerField(required=False,allow_null=True)
    submittedDate = serializers.DateTimeField(required=False, allow_null=True)


    mediaType = serializers.IntegerField(required=True)
    isRejected = serializers.BooleanField(default=False)
    firstName = serializers.CharField(required=False,allow_blank=True)
    middleName = serializers.CharField(required=False,allow_blank=True)
    lastName = serializers.CharField(required=False,allow_blank=True)
    phoneNumber = serializers.CharField(required=False,allow_blank=True)
    address = serializers.CharField(required=False,allow_blank=True)
    city = serializers.CharField(required=False,allow_blank=True)
    stateAB = serializers.CharField(required=False,allow_blank=True,allow_null=True)
    zip = serializers.CharField(required=False,allow_blank=True)
    vehicleYear = serializers.CharField(required=False,allow_blank=True)
    make = serializers.CharField(required=False,allow_blank=True)
    model = serializers.CharField(required=False,allow_blank=True)
    color = serializers.CharField(required=False,allow_blank=True)
    vinNumber = serializers.CharField(required=False,allow_blank=True)
    note = serializers.CharField(required=False,allow_blank=True)
    isWarning = serializers.BooleanField(default=True)
    rejectId = serializers.IntegerField(allow_null=True)
    licensePlate = serializers.CharField(required=False,allow_blank=True)
    speedPic = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    platePic = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    licenseStateId = serializers.IntegerField(required=True)
    locationId = serializers.IntegerField(required=True,allow_null=False)
    postedSpeed = serializers.IntegerField(required=True,allow_null=False)
    violatedSpeed = serializers.IntegerField(required=False,allow_null=True)
    distance = serializers.IntegerField(required=False,allow_null=True)
    fineId = serializers.IntegerField(required=True,allow_null=False)
    citationID = serializers.CharField(required=False,allow_blank=True,allow_null=True)