# Generated by Django 4.2.6 on 2024-10-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0038_image_custom_counter_image_station_and_more'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_stations', to='video.city'),
        ),
    ]
