# Generated by Django 4.2.6 on 2024-12-23 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0038_image_custom_counter_image_station_and_more'),
        ('accounts', '0003_station_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_users', to='video.agency'),
        ),
    ]
