# Generated by Django 4.2.6 on 2024-12-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionlevel',
            name='isAddRoadLocationView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isAddUserView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isApprovedTableView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isCSVView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isEditFineView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isRejectView',
            field=models.BooleanField(default=False),
        ),
    ]
