# Generated by Django 4.2.6 on 2025-01-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_permissionlevel_isaddroadlocationview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionlevel',
            name='isAddCourtDate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isCourtPreview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isSubmissionView',
            field=models.BooleanField(default=False),
        ),
    ]
