# Generated by Django 4.2.6 on 2025-05-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_permissionlevel_isaddcourtdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionlevel',
            name='isAgencyAdjudicationBinView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isODRView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isPreODRView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isReviewBinView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isViewReportView',
            field=models.BooleanField(default=False),
        ),
    ]
