# Generated by Django 4.2.6 on 2025-05-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_permissionlevel_isagencyadjudicationbinview_and_more'),
        ('accounts', '0008_permissionlevel_isodrview_and_more'),
    ]

    operations = [
    ]
