# Generated by Django 4.2.6 on 2025-10-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20250520_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionlevel',
            name='isReminderView',
            field=models.BooleanField(default=False),
        ),
    ]
