# Generated by Django 4.2.6 on 2025-10-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_permissionlevel_isreminderview'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionlevel',
            name='isDailyReport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='isTotalTicket',
            field=models.BooleanField(default=False),
        ),
    ]
