from rest_framework import serializers


class SubmitAdjudicatorInputModel(serializers.Serializer):
    mediaType = serializers.IntegerField(required=True)
    isAdjudicated = serializers.BooleanField(default=False)
    isRejected = serializers.BooleanField(default=False)
    videoId = serializers.IntegerField(required=False,allow_null=True)
    imageId = serializers.IntegerField(required=False,allow_null=True)
    tattileId = serializers.IntegerField(required=False,allow_null=True)
    firstName = serializers.CharField(required=False,allow_blank=True)
    middleName = serializers.CharField(required=False,allow_blank=True)
    lastName = serializers.CharField(required=False,allow_blank=True)
    phoneNumber = serializers.CharField(required=False,allow_blank=True)
    address = serializers.CharField(required=False,allow_blank=True)
    city = serializers.CharField(required=False,allow_blank=True)
    stateAB = serializers.CharField(required=False,allow_blank=True)
    zip = serializers.CharField(required=False,allow_blank=True)
    vehicleYear = serializers.CharField(required=False,allow_blank=True)
    make = serializers.CharField(required=False,allow_blank=True)
    model = serializers.CharField(required=False,allow_blank=True)
    color = serializers.CharField(required=False,allow_blank=True)
    vinNumber = serializers.CharField(required=False,allow_blank=True)
    note = serializers.CharField(required=False,allow_blank=True)
    isWarning = serializers.BooleanField(default=True)
    rejectId = serializers.IntegerField(allow_null=True)
    licensePlate =serializers.CharField(required=False,allow_blank=True)
    speedPic = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    platePic = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    licenseStateId = serializers.IntegerField(required=True)
    locationId = serializers.IntegerField(required=True,allow_null=False)
    postedSpeed = serializers.IntegerField(required=True,allow_null=False)
    violatedSpeed = serializers.IntegerField(required=False,allow_null=True)
    distance = serializers.IntegerField(required=False,allow_null=True,default=0)
    fineId = serializers.IntegerField(required=True,allow_null=False)
    citationID = serializers.CharField(required=False,allow_blank=True,allow_null=True)
    isSentToReviewBin = serializers.BooleanField(default=False)

class GetPreSignedUrlBase64StringInputModel(serializers.Serializer):
    mediaId = serializers.IntegerField()
    mediaType = serializers.IntegerField()


class GetVideoBase64StringOutputModel(serializers.Serializer):
    imageBase64Strings = serializers.ListField(child=serializers.CharField(),allow_empty=True)

class GetImageBase64StringOutputModel(serializers.Serializer):
    imageBase64Strings = serializers.ListField(child=serializers.CharField(),allow_empty=True)


class GetAdjudicationMediaDataInputModel(serializers.Serializer):
    mediaId = serializers.IntegerField(required=True)
    mediaType = serializers.IntegerField(required=True)


class GetAdjudicationViewVideoDataByIdModel(serializers.Serializer):
    id = serializers.IntegerField()
    url = serializers.CharField()
    violatingSpeed = serializers.IntegerField()
    datetime = serializers.DateTimeField()
    stationId = serializers.IntegerField()
    locationId = serializers.IntegerField()
    locationName = serializers.CharField()
    locationCode = serializers.IntegerField()
    postedSpeed = serializers.IntegerField()
    isSchoolZone = serializers.BooleanField()
    stateRS = serializers.CharField()
    stateId = serializers.IntegerField()
    stateName = serializers.CharField()
    stateAB = serializers.CharField()
    fineId = serializers.IntegerField()
    fineAmount = serializers.IntegerField()
    distance = serializers.IntegerField()
    licensePlate = serializers.CharField(allow_blank=True)
    speedPic = serializers.CharField(required=False,allow_blank=True)
    platePic = serializers.CharField(required=False,allow_blank=True)
    firstName = serializers.CharField(required=False,allow_blank=True)
    middleName = serializers.CharField(required=False,allow_blank=True)
    lastName = serializers.CharField(required=False,allow_blank=True)
    address = serializers.CharField(required=False,allow_blank=True)
    city = serializers.CharField(required=False,allow_blank=True)
    personStateAB = serializers.CharField(required=False,allow_blank=True)
    personState = serializers.CharField(required=False,allow_blank=True)
    zip = serializers.CharField(required=False,allow_blank=True)
    vehicleYear = serializers.CharField(required=False,allow_blank=True)
    make = serializers.CharField(required=False,allow_blank=True)
    model = serializers.CharField(required=False,allow_blank=True)
    color = serializers.CharField(required=False,allow_blank=True)
    vinNumber = serializers.CharField(required=False,allow_blank=True)
    isWarning = serializers.BooleanField()
    note = serializers.CharField(required=False,allow_blank=True)
    citationId = serializers.CharField(required=False,allow_blank=True)
    citationID = serializers.CharField(required=False,allow_blank=True)
    isRejected = serializers.BooleanField()
    isAdjudicated = serializers.BooleanField()
    isSent = serializers.BooleanField()
    isSentToReviewBin = serializers.BooleanField()


class GetAdjudicationViewImageDataByIdModel(serializers.Serializer):
    id = serializers.IntegerField()
    ticketId = serializers.IntegerField(allow_null=True)
    time = serializers.DateTimeField()
    data = serializers.CharField()
    speed = serializers.IntegerField(allow_null=True)
    violatingSpeed = serializers.IntegerField(allow_null=True)
    citationId = serializers.IntegerField(allow_null=True)
    licenseImageUrl = serializers.CharField(allow_blank=True)
    speedImageUrl = serializers.CharField(allow_blank=True)
    stationId = serializers.IntegerField(allow_null=True)
    locationId = serializers.IntegerField(allow_null=True)
    locationName = serializers.CharField(allow_blank=True)
    locationCode = serializers.IntegerField(allow_null=True)
    postedSpeed = serializers.IntegerField(allow_null=True)
    isSchoolZone = serializers.BooleanField()
    stateRS = serializers.CharField()
    stateId = serializers.IntegerField(allow_null=True)
    stateName = serializers.CharField(allow_blank=True)
    stateAB = serializers.CharField(allow_blank=True)
    imageUrls = serializers.ListField(child=serializers.CharField(),allow_empty=True)
    fineId = serializers.IntegerField(allow_null=True)
    fineAmount = serializers.IntegerField(allow_null=True)
    distance = serializers.IntegerField(allow_null=True)
    licensePlate = serializers.CharField(allow_blank=True)
    speedPic = serializers.CharField(required=False,allow_blank=True)
    platePic = serializers.CharField(required=False,allow_blank=True)
    firstName = serializers.CharField(required=False,allow_blank=True)
    middleName = serializers.CharField(required=False,allow_blank=True)
    lastName = serializers.CharField(required=False,allow_blank=True)
    address = serializers.CharField(required=False,allow_blank=True)
    city = serializers.CharField(required=False,allow_blank=True)
    personStateAB = serializers.CharField(required=False,allow_blank=True)
    personState = serializers.CharField(required=False,allow_blank=True)
    zip = serializers.CharField(required=False,allow_blank=True)
    vehicleYear = serializers.CharField(required=False,allow_blank=True)
    make = serializers.CharField(required=False,allow_blank=True)
    model = serializers.CharField(required=False,allow_blank=True)
    color = serializers.CharField(required=False,allow_blank=True)
    vinNumber = serializers.CharField(required=False,allow_blank=True)
    isWarning = serializers.BooleanField()
    note = serializers.CharField(required=False,allow_blank=True)
    citationId = serializers.CharField(required=False,allow_blank=True)
    citationID = serializers.CharField(required=False,allow_blank=True)
    isRejected = serializers.BooleanField()
    isAdjudicated = serializers.BooleanField()
    isSent = serializers.BooleanField()
    isSentToReviewBin = serializers.BooleanField()


class GetAdjudicationViewTattileDataByIdModel(serializers.Serializer):
    id = serializers.IntegerField()
    ticketId = serializers.CharField(required=False,allow_blank=True)
    time = serializers.DateTimeField()
    data = serializers.CharField()
    speed = serializers.IntegerField(allow_null=True)
    violatingSpeed = serializers.IntegerField(allow_null=True)
    citationId = serializers.IntegerField(allow_null=True)
    licenseImageUrl = serializers.CharField(allow_blank=True)
    speedImageUrl = serializers.CharField(allow_blank=True)
    stationId = serializers.IntegerField(allow_null=True)
    locationId = serializers.IntegerField(allow_null=True)
    locationName = serializers.CharField(allow_blank=True)
    locationCode = serializers.IntegerField(allow_null=True)
    postedSpeed = serializers.IntegerField(allow_null=True)
    isSchoolZone = serializers.BooleanField()
    stateRS = serializers.CharField()
    stateId = serializers.IntegerField(allow_null=True)
    stateName = serializers.CharField(allow_blank=True)
    stateAB = serializers.CharField(allow_blank=True)
    imageUrls = serializers.ListField(child=serializers.CharField(),allow_empty=True)
    fineId = serializers.IntegerField(allow_null=True)
    fineAmount = serializers.IntegerField(allow_null=True)
    distance = serializers.IntegerField(allow_null=True)
    licensePlate = serializers.CharField(allow_blank=True)
    speedPic = serializers.CharField(required=False,allow_blank=True)
    platePic = serializers.CharField(required=False,allow_blank=True)
    firstName = serializers.CharField(required=False,allow_blank=True)
    middleName = serializers.CharField(required=False,allow_blank=True)
    lastName = serializers.CharField(required=False,allow_blank=True)
    address = serializers.CharField(required=False,allow_blank=True)
    city = serializers.CharField(required=False,allow_blank=True)
    personStateAB = serializers.CharField(required=False,allow_blank=True)
    personState = serializers.CharField(required=False,allow_blank=True)
    zip = serializers.CharField(required=False,allow_blank=True)
    vehicleYear = serializers.CharField(required=False,allow_blank=True)
    make = serializers.CharField(required=False,allow_blank=True)
    model = serializers.CharField(required=False,allow_blank=True)
    color = serializers.CharField(required=False,allow_blank=True)
    vinNumber = serializers.CharField(required=False,allow_blank=True)
    isWarning = serializers.BooleanField()
    note = serializers.CharField(required=False,allow_blank=True)
    citationId = serializers.CharField(required=False,allow_blank=True)
    citationID = serializers.CharField(required=False,allow_blank=True)
    isRejected = serializers.BooleanField()
    isAdjudicated = serializers.BooleanField()
    isSent = serializers.BooleanField()
    isSentToReviewBin = serializers.BooleanField() 
    

class GetMediaDataInputModel(serializers.Serializer):
    mediaId = serializers.IntegerField(required=True)
    mediaType = serializers.IntegerField(required=True)


class GetNewCitationID(serializers.Serializer):
    citationID = serializers.CharField()


class PresignedUrlInputModel(serializers.Serializer):
    preSignedUrl = serializers.CharField(allow_blank=True,required=False)


class GetBase64StringResponseModel(serializers.Serializer):
    base64String = serializers.CharField(allow_blank=True,required=False)

class GetFineViewInputModel(serializers.Serializer):
    posted_speed = serializers.IntegerField(required=True)
    violated_speed = serializers.IntegerField(required=True)
    mediaId = serializers.IntegerField(required=True)
    mediaType = serializers.IntegerField(required=True)
    

class GetFineViewResponseModel(serializers.Serializer):
    fine_amount = serializers.IntegerField()
    fine_id = serializers.IntegerField()
    posted_speed = serializers.IntegerField()
    violated_speed = serializers.IntegerField()