from rest_framework import serializers

class SubmitAgencyAdjudicationBinViewInputModel(serializers.Serializer):
    isAdjudicatedInAgencyAdjudicationBin = serializers.BooleanField(default=False)
    isRejectedInAgencyAdjudicationBin = serializers.BooleanField(default=False)

    videoId = serializers.IntegerField(required=False,allow_null=True)
    imageId = serializers.IntegerField(required=False,allow_null=True)
    
    tattileId = serializers.IntegerField(required=False,allow_null=True)
    submittedDate = serializers.DateTimeField(required=False,allow_null=True)


    mediaType = serializers.IntegerField(required=True)
    isRejected = serializers.BooleanField(default=False)
    firstName = serializers.CharField(required=False,allow_blank=True)
    middleName = serializers.CharField(required=False,allow_blank=True)
    lastName = serializers.CharField(required=False,allow_blank=True)
    phoneNumber = serializers.CharField(required=False,allow_blank=True)
    address = serializers.CharField(required=False,allow_blank=True)
    city = serializers.CharField(required=False,allow_blank=True)
    stateAB = serializers.CharField(required=False,allow_blank=True, allow_null=True)
    zip = serializers.CharField(required=False,allow_blank=True)
    vehicleYear = serializers.CharField(required=False,allow_blank=True)
    make = serializers.CharField(required=False,allow_blank=True)
    model = serializers.CharField(required=False,allow_blank=True)
    color = serializers.CharField(required=False,allow_blank=True)
    vinNumber = serializers.CharField(required=False,allow_blank=True)
    note = serializers.CharField(required=False,allow_blank=True)
    isWarning = serializers.BooleanField(default=True)
    rejectId = serializers.IntegerField(allow_null=True)
    licensePlate = serializers.CharField(required=False,allow_blank=True)
    speedPic = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    platePic = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    licenseStateId = serializers.IntegerField(required=True)
    locationId = serializers.IntegerField(required=True,allow_null=False)
    postedSpeed = serializers.IntegerField(required=True,allow_null=False)
    violatedSpeed = serializers.IntegerField(required=False,allow_null=True)
    distance = serializers.IntegerField(required=False,allow_null=True)
    fineId = serializers.IntegerField(required=True,allow_null=False)
    citationID = serializers.CharField(required=False,allow_blank=True,allow_null=True)

class GetAgencyAdjudicationMediaDataInputModel(serializers.Serializer):
    mediaId = serializers.IntegerField(required=True)
    mediaType = serializers.IntegerField(required=True)


class GetAgencyAdjudicationViewVideoDataByIdModel(serializers.Serializer):
    id = serializers.IntegerField()
    url = serializers.CharField()
    violatingSpeed = serializers.IntegerField()
    datetime = serializers.DateTimeField()
    stationId = serializers.IntegerField()
    locationId = serializers.IntegerField()
    locationName = serializers.CharField()
    locationCode = serializers.IntegerField()
    postedSpeed = serializers.IntegerField()
    isSchoolZone = serializers.BooleanField()
    stateRS = serializers.CharField()
    stateId = serializers.IntegerField()
    stateName = serializers.CharField()
    stateAB = serializers.CharField()
    fineId = serializers.IntegerField()
    fineAmount = serializers.IntegerField()
    distance = serializers.IntegerField()
    licensePlate = serializers.CharField(allow_blank=True)
    speedPic = serializers.CharField(required=False,allow_blank=True)
    platePic = serializers.CharField(required=False,allow_blank=True)
    firstName = serializers.CharField(required=False,allow_blank=True)
    middleName = serializers.CharField(required=False,allow_blank=True)
    lastName = serializers.CharField(required=False,allow_blank=True)
    address = serializers.CharField(required=False,allow_blank=True)
    city = serializers.CharField(required=False,allow_blank=True)
    personStateAB = serializers.CharField(required=False,allow_blank=True)
    personState = serializers.CharField(required=False,allow_blank=True)
    zip = serializers.CharField(required=False,allow_blank=True)
    vehicleYear = serializers.CharField(required=False,allow_blank=True)
    make = serializers.CharField(required=False,allow_blank=True)
    model = serializers.CharField(required=False,allow_blank=True)
    color = serializers.CharField(required=False,allow_blank=True)
    vinNumber = serializers.CharField(required=False,allow_blank=True)
    isWarning = serializers.BooleanField()
    note = serializers.CharField(required=False,allow_blank=True)
    citationId = serializers.CharField(required=False,allow_blank=True)
    citationID = serializers.CharField(required=False,allow_blank=True)
    isRejected = serializers.BooleanField()
    isAdjudicated = serializers.BooleanField()
    isSent = serializers.BooleanField()
    isSentToReviewBin = serializers.BooleanField()



class GetAgencyAdjudicationViewImageDataByIdModel(serializers.Serializer):
    id = serializers.IntegerField()
    ticketId = serializers.IntegerField()
    time = serializers.DateTimeField()
    data = serializers.CharField()
    speed = serializers.IntegerField()
    violatingSpeed = serializers.IntegerField()
    citationId = serializers.IntegerField()
    licenseImageUrl = serializers.CharField()
    speedImageUrl = serializers.CharField()
    stationId = serializers.IntegerField()
    locationId = serializers.IntegerField()
    locationName = serializers.CharField()
    locationCode = serializers.IntegerField()
    postedSpeed = serializers.IntegerField()
    isSchoolZone = serializers.BooleanField()
    stateRS = serializers.CharField()
    stateId = serializers.IntegerField()
    stateName = serializers.CharField()
    stateAB = serializers.CharField()
    imageUrls = serializers.ListField(child=serializers.CharField(),allow_empty=True)
    fineId = serializers.IntegerField()
    fineAmount = serializers.IntegerField()
    distance = serializers.IntegerField()
    licensePlate = serializers.CharField(allow_blank=True)
    speedPic = serializers.CharField(required=False,allow_blank=True)
    platePic = serializers.CharField(required=False,allow_blank=True)
    firstName = serializers.CharField(required=False,allow_blank=True)
    middleName = serializers.CharField(required=False,allow_blank=True)
    lastName = serializers.CharField(required=False,allow_blank=True)
    address = serializers.CharField(required=False,allow_blank=True)
    city = serializers.CharField(required=False,allow_blank=True)
    personStateAB = serializers.CharField(required=False,allow_blank=True)
    personState = serializers.CharField(required=False,allow_blank=True)
    zip = serializers.CharField(required=False,allow_blank=True)
    vehicleYear = serializers.CharField(required=False,allow_blank=True)
    make = serializers.CharField(required=False,allow_blank=True)
    model = serializers.CharField(required=False,allow_blank=True)
    color = serializers.CharField(required=False,allow_blank=True)
    vinNumber = serializers.CharField(required=False,allow_blank=True)
    isWarning = serializers.BooleanField()
    note = serializers.CharField(required=False,allow_blank=True)
    citationId = serializers.CharField(required=False,allow_blank=True)
    citationID = serializers.CharField(required=False,allow_blank=True)
    isRejected = serializers.BooleanField()
    isAdjudicated = serializers.BooleanField()
    isSent = serializers.BooleanField()
    isSentToReviewBin = serializers.BooleanField()
    

class GetAgencyAdjudicationViewTattileDataByIdModel(serializers.Serializer):
    id = serializers.IntegerField()
    ticketId = serializers.CharField()
    time = serializers.DateTimeField()
    data = serializers.CharField()
    speed = serializers.IntegerField()
    violatingSpeed = serializers.IntegerField()
    citationId = serializers.IntegerField()
    licenseImageUrl = serializers.CharField()
    speedImageUrl = serializers.CharField()
    stationId = serializers.IntegerField()
    locationId = serializers.IntegerField()
    locationName = serializers.CharField()
    locationCode = serializers.IntegerField()
    postedSpeed = serializers.IntegerField()
    isSchoolZone = serializers.BooleanField()
    stateRS = serializers.CharField()
    stateId = serializers.IntegerField()
    stateName = serializers.CharField()
    stateAB = serializers.CharField()
    imageUrls = serializers.ListField(child=serializers.CharField(),allow_empty=True)
    fineId = serializers.IntegerField()
    fineAmount = serializers.IntegerField()
    distance = serializers.IntegerField()
    licensePlate = serializers.CharField(allow_blank=True)
    speedPic = serializers.CharField(required=False,allow_blank=True)
    platePic = serializers.CharField(required=False,allow_blank=True)
    firstName = serializers.CharField(required=False,allow_blank=True)
    middleName = serializers.CharField(required=False,allow_blank=True)
    lastName = serializers.CharField(required=False,allow_blank=True)
    address = serializers.CharField(required=False,allow_blank=True)
    city = serializers.CharField(required=False,allow_blank=True)
    personStateAB = serializers.CharField(required=False,allow_blank=True)
    personState = serializers.CharField(required=False,allow_blank=True)
    zip = serializers.CharField(required=False,allow_blank=True)
    vehicleYear = serializers.CharField(required=False,allow_blank=True)
    make = serializers.CharField(required=False,allow_blank=True)
    model = serializers.CharField(required=False,allow_blank=True)
    color = serializers.CharField(required=False,allow_blank=True)
    vinNumber = serializers.CharField(required=False,allow_blank=True)
    isWarning = serializers.BooleanField()
    note = serializers.CharField(required=False,allow_blank=True)
    citationId = serializers.CharField(required=False,allow_blank=True)
    citationID = serializers.CharField(required=False,allow_blank=True)
    isRejected = serializers.BooleanField()
    isAdjudicated = serializers.BooleanField()
    isSent = serializers.BooleanField()
    isSentToReviewBin = serializers.BooleanField()


class GetAgencyAdjudicationMediaDataInputModel(serializers.Serializer):
    mediaId = serializers.IntegerField(required=True)
    mediaType = serializers.IntegerField(required=True)
