# Generated by Django 4.2.6 on 2024-01-10 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citationID', models.CharField(max_length=100, unique=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_speed', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('speed_pic', models.CharField(blank=True, max_length=500)),
                ('plate_pic', models.CharField(blank=True, max_length=500)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('isApproved', models.BooleanField(default=False)),
                ('isRejected', models.BooleanField(default=False)),
                ('isSendBack', models.BooleanField(default=False)),
                ('isRemoved', models.BooleanField(default=False)),
                ('dist', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'citation',
            },
        ),
        migrations.CreateModel(
            name='csv_metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'csv_metadata',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('PK', models.TextField(primary_key=True, serialize=False)),
                ('VIDEO_NO', models.TextField()),
                ('VIDEO_NAME', models.TextField()),
                ('FRAMES', models.IntegerField()),
                ('DATE', models.TextField()),
                ('TIME', models.TextField()),
                ('SPEED_LIMIT', models.IntegerField()),
                ('SPEED', models.IntegerField()),
                ('DISTANCE', models.IntegerField(null=True)),
                ('BADGE_ID', models.TextField(blank=True)),
                ('LOCATION_CODE', models.IntegerField(null=True)),
                ('STATION', models.CharField(blank=True)),
            ],
            options={
                'db_table': 'video_data',
            },
        ),
        migrations.CreateModel(
            name='pdf_metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('zipLocation', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'pdf_metadata',
            },
        ),
        migrations.CreateModel(
            name='Rejects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'rejects',
            },
        ),
        migrations.CreateModel(
            name='road_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOCATION_CODE', models.IntegerField(null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('posted_speed', models.IntegerField()),
                ('isSchoolZone', models.BooleanField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_road_locations', to='accounts.station')),
            ],
            options={
                'db_table': 'road_location',
                'unique_together': {('station', 'LOCATION_CODE')},
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ab', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIDEO_NO', models.TextField(blank=True)),
                ('caption', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('posted_speed', models.IntegerField(blank=True)),
                ('speed', models.IntegerField(blank=True)),
                ('speed_time', models.DecimalField(blank=True, decimal_places=20, max_digits=100)),
                ('distance', models.IntegerField(blank=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('isRejected', models.BooleanField(default=False)),
                ('isAdjudicated', models.BooleanField(default=False)),
                ('isRemoved', models.BooleanField(default=False)),
                ('officer_badge', models.TextField(blank=True)),
                ('isSent', models.BooleanField(default=False)),
                ('citation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citation_videos', to='video.citation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_videos', to='video.road_location')),
                ('reject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reject_videos', to='video.rejects')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_videos', to='accounts.station')),
            ],
            options={
                'db_table': 'video',
                'unique_together': {('station', 'VIDEO_NO')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=200)),
                ('lic_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lic_state_vehicles', to='video.state')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_vehicles', to='accounts.station')),
            ],
            options={
                'db_table': 'vehicle',
                'unique_together': {('station', 'vehicle_id')},
            },
        ),
        migrations.CreateModel(
            name='sup_metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApproved', models.BooleanField()),
                ('timeApp', models.DateTimeField(default=django.utils.timezone.now)),
                ('isRemoved', models.BooleanField(default=False)),
                ('timeRemoved', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('citation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_sup_metadata', to='video.citation')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_sup_metadata', to='accounts.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sup_metadata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sup_metadata',
            },
        ),
        migrations.CreateModel(
            name='SMTP_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPdfSent', models.BooleanField()),
                ('dateTimePdfSent', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateTimeCsvSent', models.DateTimeField(default=django.utils.timezone.now)),
                ('csvFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_smtp_data', to='video.csv_metadata')),
                ('pdfFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_smtp_data', to='video.pdf_metadata')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_smtp_data', to='accounts.station')),
            ],
            options={
                'db_table': 'smtp_data',
            },
        ),
        migrations.CreateModel(
            name='QuickPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_date', models.CharField(max_length=100)),
                ('offense_time', models.CharField(blank=True, max_length=100)),
                ('ticket_num', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=200)),
                ('middle', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=200)),
                ('generation', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(blank=True, max_length=50)),
                ('dob', models.CharField(blank=True, default='01012001', max_length=8)),
                ('race', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('ssn', models.CharField(blank=True, max_length=20, null=True)),
                ('dl', models.CharField(blank=True, default='1', max_length=20)),
                ('dl_state', models.CharField(blank=True, default='LA', max_length=2)),
                ('accident', models.CharField(blank=True, max_length=20, null=True)),
                ('comm', models.CharField(blank=True, max_length=20, null=True)),
                ('vehder', models.CharField(blank=True, max_length=20, null=True)),
                ('arraignment_date', models.CharField(max_length=100)),
                ('actual_speed', models.IntegerField(null=True)),
                ('posted_speed', models.IntegerField(null=True)),
                ('officer_badge', models.TextField(blank=True)),
                ('street1_id', models.CharField(blank=True, max_length=20, null=True)),
                ('street2_id', models.CharField(blank=True, max_length=20, null=True)),
                ('street1_name', models.CharField(blank=True, max_length=200, null=True)),
                ('street2_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bac', models.CharField(blank=True, max_length=20, null=True)),
                ('test_type', models.CharField(blank=True, max_length=20, null=True)),
                ('plate_num', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_state', models.CharField(blank=True, max_length=2, null=True)),
                ('vin', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('radar', models.CharField(blank=True, default='0', max_length=20)),
                ('state_rs1', models.CharField(blank=True, max_length=20, null=True)),
                ('state_rs2', models.CharField(blank=True, max_length=20, null=True)),
                ('state_rs3', models.CharField(blank=True, max_length=20, null=True)),
                ('state_rs4', models.CharField(blank=True, max_length=20, null=True)),
                ('state_rs5', models.CharField(blank=True, max_length=20, null=True)),
                ('warning', models.CharField(blank=True, max_length=3, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('dl_class', models.CharField(blank=True, max_length=20, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_quickpds', to='accounts.station')),
            ],
            options={
                'db_table': 'quickpd',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=50)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_persons', to='accounts.station')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.AddField(
            model_name='pdf_metadata',
            name='quickPD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickPD_pdf_metadata', to='video.quickpd'),
        ),
        migrations.AddField(
            model_name='pdf_metadata',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_pdf_metadata', to='accounts.station'),
        ),
        migrations.AddField(
            model_name='pdf_metadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pdf_metadata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_diff', models.IntegerField()),
                ('fine', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rs_code', models.CharField(max_length=20)),
                ('isSchoolZone', models.BooleanField(default=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_fines', to='accounts.station')),
            ],
            options={
                'db_table': 'fine',
            },
        ),
        migrations.CreateModel(
            name='dmv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.TextField(blank=True)),
                ('raw', models.TextField(blank=True, null=True)),
                ('state_ab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_dmv', to='video.state')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_dmv', to='accounts.station')),
            ],
            options={
                'db_table': 'dmv',
            },
        ),
        migrations.AddField(
            model_name='csv_metadata',
            name='quickPD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickPD_csv_metadata', to='video.quickpd'),
        ),
        migrations.AddField(
            model_name='csv_metadata',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_csv_metadata', to='accounts.station'),
        ),
        migrations.AddField(
            model_name='csv_metadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_csv_metadata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourtDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_string', models.CharField(max_length=20)),
                ('c_date', models.DateField(null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_court_dates', to='accounts.station')),
            ],
            options={
                'db_table': 'court_dates',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_cities', to='video.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.AddField(
            model_name='citation',
            name='court_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_date_citations', to='video.courtdates'),
        ),
        migrations.AddField(
            model_name='citation',
            name='fine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_citations', to='video.fine'),
        ),
        migrations.AddField(
            model_name='citation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_citations', to='video.road_location'),
        ),
        migrations.AddField(
            model_name='citation',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_citations', to='video.person'),
        ),
        migrations.AddField(
            model_name='citation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_citations', to='accounts.station'),
        ),
        migrations.AddField(
            model_name='citation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_citations', to='video.vehicle'),
        ),
        migrations.AddField(
            model_name='citation',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_citations', to='video.video'),
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('onboarding_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=200)),
                ('device_id', models.CharField(max_length=20)),
                ('ORI', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('address_2', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('badge_url', models.URLField(blank=True, max_length=500, null=True)),
                ('state_rs', models.CharField(blank=True, max_length=500)),
                ('pay_portal', models.CharField(blank=True, max_length=500)),
                ('court_comments', models.TextField(blank=True)),
                ('emails', models.TextField(blank=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_agencies', to='accounts.station')),
            ],
            options={
                'db_table': 'agency',
            },
        ),
        migrations.CreateModel(
            name='adj_metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citationID', models.CharField(blank=True, default='', max_length=100)),
                ('timeAdj', models.DateTimeField(default=django.utils.timezone.now)),
                ('isRemoved', models.BooleanField(default=False)),
                ('timeRemoved', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('citation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citation_adj_metadata', to='video.citation')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_adj_metadata', to='accounts.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_adj_metadata', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_adj_metadata', to='video.video')),
            ],
            options={
                'db_table': 'adj_metadata',
            },
        ),
    ]
