# Generated by Django 4.2.6 on 2024-04-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='citation',
    #         name='is_warning',
    #         field=models.BooleanField(default=False),
    #     ),
    # ]
