# Generated by Django 4.2.6 on 2023-12-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='video',
    #         name='citation',
    #         field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citation_videos', to='video.citation'),
    #     ),
    # ]
