# Generated by Django 4.2.6 on 2024-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_citation_is_warning'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='citation',
    #         name='captured_date',
    #         field=models.DateTimeField(null=True),
    #     ),
    # ]
