# Generated by Django 4.2.6 on 2024-03-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='is_warning',
            field=models.BooleanField(default=False),
        ),
    ]
