# Generated by Django 4.2.6 on 2024-03-16 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('ticket_id', models.IntegerField(blank=True, null=True)),
                ('location_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=20)),
                ('plate_image_filename', models.CharField(max_length=200)),
                ('plate_text', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('zip', models.TextField(blank=True, null=True)),
                ('current_speed_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('violating_speed', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'image_data',
            },
        ),
        migrations.CreateModel(
            name='ImageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state_code', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'Imagestate',
            },
        ),
        migrations.CreateModel(
            name='ImageCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_cities', to='video.imagestate')),
            ],
            options={
                'db_table': 'Imagecity',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('image_name', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('is_Rejected', models.BooleanField(default=False)),
                ('is_Adjudicated', models.BooleanField(default=False)),
                ('is_Removed', models.BooleanField(default=False)),
                ('isSent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('citation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citation_images', to='video.citation')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities_name', to='video.imagecity')),
                ('reject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reject_image', to='video.rejects')),
            ],
            options={
                'db_table': 'Image',
            },
        ),
    ]
