# Generated by Django 4.2.6 on 2024-03-17 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_imagedata_imagestate_imagecity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageNew',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_id', models.BigIntegerField()),
                ('location_id', models.BigIntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.CharField()),
                ('current_speed_limit', models.IntegerField()),
                ('violating_speed', models.FloatField()),
                ('plate_text', models.CharField(max_length=50)),
                ('locked', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocr_status', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('modelId', models.IntegerField()),
                ('hash', models.CharField()),
                ('password', models.CharField()),
                ('validation_status_name', models.CharField(max_length=100)),
                ('validation_name_color', models.CharField(max_length=100)),
                ('camera_name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=1000)),
                ('plate_image_filename', models.CharField(max_length=1000)),
                ('speed_unit', models.CharField(max_length=10)),
                ('location_name', models.CharField(max_length=1000)),
                ('static_url', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'image_new',
            },
        ),
    ]
