# Generated by Django 4.2.6 on 2024-03-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_imagenew'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDataNew',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_id', models.BigIntegerField()),
                ('image_name', models.CharField()),
                ('image_url', models.CharField()),
            ],
            options={
                'db_table': 'image_data_new',
            },
        ),
    ]
