# Generated by Django 4.2.6 on 2024-03-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_imagedatanew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='image',
            name='city',
        ),
        migrations.RemoveField(
            model_name='image',
            name='reject',
        ),
        migrations.RemoveField(
            model_name='imagecity',
            name='state',
        ),
        migrations.DeleteModel(
            name='ImageData',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageCity',
        ),
        migrations.DeleteModel(
            name='ImageState',
        ),
    ]
