# Generated by Django 4.2.6 on 2024-03-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_remove_image_citation_remove_image_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageNew',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='ImageDataNew',
            new_name='ImageData',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
        migrations.AlterModelTable(
            name='imagedata',
            table='image_data',
        ),
    ]
