# Generated by Django 4.2.6 on 2024-03-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_rename_imagenew_image_rename_imagedatanew_imagedata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('radar_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=50)),
                ('contact_user_id', models.IntegerField()),
                ('timezone_id', models.IntegerField()),
                ('direction', models.CharField(max_length=100)),
                ('group_id', models.IntegerField()),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('tz', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'image_location',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='isAdjudicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='isRejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='isRemoved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='isSent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='reject',
            field=models.IntegerField(null=True),
        ),
    ]
