# Generated by Django 4.2.6 on 2024-03-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_imagelocation_image_isadjudicated_image_isrejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelocation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
