# Generated by Django 4.2.6 on 2024-03-19 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_alter_imagelocation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_citations', to='video.image'),
        ),
        migrations.AddField(
            model_name='image',
            name='citation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citation_images', to='video.citation'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_citations', to='video.video'),
        ),
    ]
