# Generated by Django 4.2.6 on 2024-03-19 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_citation_image_image_citation_alter_citation_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='adj_metadata',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_adj_metadata', to='video.image'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_citations', to='video.road_location'),
        ),
    ]
