# Generated by Django 4.2.6 on 2024-03-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_adj_metadata_image_alter_citation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='reject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reject_images', to='video.rejects'),
        ),
    ]
