# Generated by Django 4.2.6 on 2024-03-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_citation_is_warning'),
        ('video', '0014_alter_image_reject'),
    ]

    operations = [
    ]
