# Generated by Django 4.2.6 on 2024-03-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_merge_20240322_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='officer_badge',
            field=models.TextField(blank=True, default=''),
        ),
    ]
