# Generated by Django 4.2.6 on 2024-03-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_image_officer_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHash',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_id', models.BigIntegerField()),
                ('image_hash', models.CharField()),
                ('image_url', models.CharField()),
            ],
            options={
                'db_table': 'image_hash',
            },
        ),
    ]
