# Generated by Django 4.2.6 on 2024-03-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_imagehash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='serial',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
