# Generated by Django 4.2.6 on 2024-03-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_alter_image_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lic_image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='speed_image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
