# Generated by Django 4.2.6 on 2024-03-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_image_lic_image_url_image_speed_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='image_location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
