# Generated by Django 4.2.6 on 2024-03-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0020_citation_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='traffic_logix_client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='traffic_logix_token',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
