# Generated by Django 4.2.6 on 2024-04-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0021_agency_traffic_logix_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='captured_date',
            field=models.DateField(null=True),
        ),
    ]
