# Generated by Django 4.2.6 on 2024-04-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0022_citation_captured_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
