# Generated by Django 4.2.6 on 2024-04-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0023_image_img_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='road_location',
            name='isTrafficLogix',
            field=models.BooleanField(null=True),
        ),
    ]
