# Generated by Django 4.2.6 on 2024-04-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0024_road_location_istrafficlogix'),
    ]

    operations = [
        migrations.AddField(
            model_name='road_location',
            name='trafficlogix_location_id',
            field=models.IntegerField(null=True),
        ),
    ]
