# Generated by Django 4.2.6 on 2024-04-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0025_road_location_trafficlogix_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFailedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_no', models.CharField(max_length=20)),
                ('video_name', models.CharField(max_length=30)),
                ('video_date', models.CharField(max_length=20)),
                ('station', models.CharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('location_code', models.CharField()),
            ],
            options={
                'db_table': 'video_failed_log',
            },
        ),
    ]
