# Generated by Django 4.2.6 on 2024-04-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_citation_captured_date'),
        ('video', '0026_videofailedlog'),
    ]

    operations = [
    ]
