# Generated by Django 4.2.6 on 2024-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0027_merge_0003_citation_captured_date_0026_videofailedlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='captured_date',
            field=models.DateField(null=True),
        ),
    ]
