# Generated by Django 4.2.6 on 2024-06-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('video', '0028_alter_citation_captured_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('station', 'VIDEO_NO', 'caption')},
        ),
    ]
