# Generated by Django 4.2.6 on 2024-06-27 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0029_alter_video_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FtpUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('s3_path', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField()),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_upload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ftp_upload_log',
            },
        ),
        migrations.CreateModel(
            name='DuncanSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSubmitted', models.BooleanField(default=False)),
                ('isRejected', models.BooleanField(default=False)),
                ('isSkipped', models.BooleanField(default=False)),
                ('lic_plate', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('veh_state', models.CharField(blank=True, max_length=50, null=True)),
                ('isSent', models.BooleanField(default=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_duncan_submission', to='video.image')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_duncan_submission', to='video.video')),
            ],
            options={
                'db_table': 'duncan_submission',
            },
        ),
    ]
