# Generated by Django 4.2.6 on 2024-07-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0030_ftpuploadlog_duncansubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuncanMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('lic_plate', models.CharField(blank=True, max_length=10, null=True)),
                ('station', models.CharField(blank=True, max_length=10, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('person_state', models.CharField(blank=True, max_length=10, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_year', models.CharField(blank=True, max_length=4, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_modle', models.CharField(blank=True, max_length=50, null=True)),
                ('vin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dunccan_data_status', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'dunccan_master_data',
            },
        ),
    ]
