# Generated by Django 4.2.6 on 2024-07-03 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0031_duncanmasterdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='duncanmasterdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='duncansubmission',
            name='isReceived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duncansubmission',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duncanmasterdata',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duncanmasterdata',
            name='dunccan_data_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duncanmasterdata',
            name='lic_plate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duncanmasterdata',
            name='person_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duncanmasterdata',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duncanmasterdata',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duncanmasterdata',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duncanmasterdata',
            name='vehicle_modle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duncanmasterdata',
            name='vehicle_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duncanmasterdata',
            name='vin_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duncanmasterdata',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
