# Generated by Django 4.2.6 on 2024-07-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0032_duncanmasterdata_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duncanmasterdata',
            name='uploaded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duncanmasterdata',
            name='vehicle_model_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
