# Generated by Django 4.2.6 on 2024-07-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0033_duncanmasterdata_uploaded_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejects',
            name='rejection_type',
            field=models.CharField(blank=True, choices=[('1', 'Adjudicator Rejects'), ('2', 'Duncan Rejects')], default=None, max_length=20, null=True),
        ),
    ]
