# Generated by Django 4.2.6 on 2024-07-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0034_rejects_rejection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='duncansubmission',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='duncansubmission',
            name='lic_plate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
