# Generated by Django 4.2.6 on 2024-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0035_duncansubmission_isapproved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='isQuickPd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='isXpressPay',
            field=models.BooleanField(default=False),
        ),
    ]
