# Generated by Django 4.2.6 on 2024-08-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0036_agency_isquickpd_agency_isxpresspay'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
