# Generated by Django 4.2.6 on 2024-09-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('video', '0037_agency_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='custom_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_images', to='accounts.station'),
        ),
        migrations.AddField(
            model_name='video',
            name='custom_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
