# Generated by Django 4.2.6 on 2024-11-29 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_station_city'),
        ('video', '0038_image_custom_counter_image_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidProcessedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('station_name', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'paid_citations_data_processed_files',
            },
        ),
        migrations.CreateModel(
            name='UnpaidCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('off_date', models.DateField(blank=True, null=True)),
                ('arr_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('isApproved', models.BooleanField(default=False)),
                ('pre_odr_mail_count', models.IntegerField(blank=True, null=True)),
                ('first_mail_due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('second_mail_due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('first_mail_fine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_mail_fine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_image', to='video.image')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_station', to='accounts.station')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_video', to='video.video')),
            ],
            options={
                'db_table': 'unpaid_citation',
            },
        ),
        migrations.CreateModel(
            name='PaidCitationsData',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('citationID', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_image_citations', to='video.image')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_video_citations', to='video.video')),
            ],
            options={
                'db_table': 'paid_citations_data',
            },
        ),
    ]
