# Generated by Django 4.2.6 on 2024-12-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0039_paidprocessedfiles_unpaidcitation_paidcitationsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidprocessedfiles',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
