# Generated by Django 4.2.6 on 2025-01-02 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_station_city'),
        ('video', '0040_alter_paidprocessedfiles_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='isPreOdr',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PreOdrXpressBillPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_date', models.CharField(max_length=100)),
                ('offense_time', models.CharField(blank=True, max_length=100)),
                ('ticket_num', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=200)),
                ('middle', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=200)),
                ('generation', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(blank=True, max_length=50)),
                ('dob', models.CharField(blank=True, default='01012001', max_length=8)),
                ('race', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('ssn', models.CharField(blank=True, max_length=20, null=True)),
                ('dl', models.CharField(blank=True, default='1', max_length=20)),
                ('dl_state', models.CharField(blank=True, default='LA', max_length=2)),
                ('accident', models.CharField(blank=True, max_length=20, null=True)),
                ('comm', models.CharField(blank=True, max_length=20, null=True)),
                ('vehder', models.CharField(blank=True, max_length=20, null=True)),
                ('arraignment_date', models.CharField(max_length=100)),
                ('actual_speed', models.IntegerField(null=True)),
                ('posted_speed', models.IntegerField(null=True)),
                ('officer_badge', models.TextField(blank=True)),
                ('street1_id', models.CharField(blank=True, max_length=20, null=True)),
                ('street2_id', models.CharField(blank=True, max_length=20, null=True)),
                ('street1_name', models.CharField(blank=True, max_length=200, null=True)),
                ('street2_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bac', models.CharField(blank=True, max_length=20, null=True)),
                ('test_type', models.CharField(blank=True, max_length=20, null=True)),
                ('plate_num', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_state', models.CharField(blank=True, max_length=2, null=True)),
                ('vin', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('radar', models.CharField(blank=True, default='0', max_length=20)),
                ('state_rs1', models.CharField(blank=True, max_length=20, null=True)),
                ('state_rs2', models.CharField(blank=True, max_length=20, null=True)),
                ('state_rs3', models.CharField(blank=True, max_length=20, null=True)),
                ('state_rs4', models.CharField(blank=True, max_length=20, null=True)),
                ('state_rs5', models.CharField(blank=True, max_length=20, null=True)),
                ('warning', models.CharField(blank=True, max_length=3, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('dl_class', models.CharField(blank=True, max_length=20, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_xpresspd', to='accounts.station')),
            ],
            options={
                'db_table': 'pre_odr_xpress_bill_pay',
            },
        ),
        migrations.CreateModel(
            name='PreOdrFineScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_mailer_fine_per', models.IntegerField(blank=True, null=True)),
                ('second_mailer_fine_per', models.IntegerField(blank=True, null=True)),
                ('first_mailer_day_gap', models.IntegerField(blank=True, null=True)),
                ('second_mailer_day_gap', models.IntegerField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_odr_fine_agency', to='video.agency')),
            ],
            options={
                'db_table': 'pre_odr_fine_scheduler',
            },
        ),
        migrations.CreateModel(
            name='PreOdrCSVMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(max_length=500, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_pre_csv_metadata', to='accounts.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pre_csv_metadata', to=settings.AUTH_USER_MODEL)),
                ('xpress_bill_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xpress_pay_pre_csv_metadata', to='video.preodrxpressbillpay')),
            ],
            options={
                'db_table': 'pre_odr_csv_metadata',
            },
        ),
    ]
