# Generated by Django 4.2.6 on 2025-01-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0041_agency_ispreodr_preodrxpressbillpay_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaidCitationsData',
        ),
    ]
