# Generated by Django 4.2.6 on 2025-01-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0042_delete_paidcitationsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidCitationsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('citationID', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_image_citations', to='video.image')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_video_citations', to='video.video')),
            ],
            options={
                'db_table': 'paid_citations',
            },
        ),
    ]
