# Generated by Django 4.2.6 on 2025-02-28 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_permissionlevel_isaddcourtdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0043_paidcitationsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickPdPaidCitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=100, unique=True)),
                ('paid_date', models.DateField(null=True)),
                ('batch_date', models.DateField(null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('court_id', models.IntegerField(null=True)),
                ('court_name', models.CharField(max_length=100, null=True)),
                ('ees_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_pd_paid_citations_image', to='video.image')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_pd_paid_citations_station', to='accounts.station')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_pd_paid_citations_video', to='video.video')),
            ],
            options={
                'db_table': 'quick_pd_paid_citations',
            },
        ),
        migrations.CreateModel(
            name='QuickPdPaidCitationFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('rows_processed', models.IntegerField()),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_pd_paid_citations_files_station', to='accounts.station')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_pd_paid_citation_files_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quick_pd_paid_citation_files',
            },
        ),
    ]
