# Generated by Django 4.2.6 on 2025-03-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0044_quickpdpaidcitations_quickpdpaidcitationfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='isZill',
            field=models.BooleanField(default=False),
        ),
    ]
