# Generated by Django 4.2.6 on 2025-04-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0045_agency_iszill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
