# Generated by Django 4.2.6 on 2025-03-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0045_agency_iszill'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpaidcitation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
