# Generated by Django 4.2.6 on 2025-04-04 06:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0045_agency_iszill'),
    ]

    operations = [
        migrations.AddField(
            model_name='duncansubmission',
            name='is_notfound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duncansubmission',
            name='is_sent_to_adjudication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duncansubmission',
            name='is_unknown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='isSentToReviewBin',
            field=models.BooleanField(default=False, help_text='sent to review bin from adjudicator view'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_notfound',
            field=models.BooleanField(default=False, help_text='This boolean field will change when is not found triggered in submissions view and will move the ticket to review bin'),
        ),
        migrations.AddField(
            model_name='video',
            name='isSentToReviewBin',
            field=models.BooleanField(default=False, help_text='sent to review bin from adjudicator view'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_notfound',
            field=models.BooleanField(default=False, help_text='This boolean field will change when is not found triggered in submissions view and ticket sent to review bin'),
        ),
        migrations.CreateModel(
            name='ReviewBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_state', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.CharField(blank=True, max_length=100, null=True)),
                ('is_notfound', models.BooleanField(default=False)),
                ('is_send_to_adj', models.BooleanField(default=False)),
                ('is_send_adjbin', models.BooleanField(default=False)),
                ('is_sent_back_subbin', models.BooleanField(default=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewbin_image', to='video.image')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewbin_video', to='video.video')),
            ],
            options={
                'db_table': 'review_bin',
            },
        ),
        migrations.CreateModel(
            name='AdjudicationBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_state', models.CharField(blank=True, max_length=50, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_adjudicated', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('station', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjudicationbin_image', to='video.image')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjudicationbin_video', to='video.video')),
            ],
            options={
                'db_table': 'adjudicated_bin',
            },
        ),
    ]
