# Generated by Django 4.2.6 on 2025-03-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0046_unpaidcitation_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='rs_code',
            field=models.CharField(max_length=50),
        ),
    ]
