# Generated by Django 4.2.6 on 2025-04-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0046_alter_quickpd_state_rs1'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='isConstructionZone',
            field=models.BooleanField(default=False),
        ),
    ]
