# Generated by Django 4.2.6 on 2025-03-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0047_alter_fine_rs_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preodrxpressbillpay',
            name='state_rs1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preodrxpressbillpay',
            name='state_rs2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preodrxpressbillpay',
            name='state_rs3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preodrxpressbillpay',
            name='state_rs4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preodrxpressbillpay',
            name='state_rs5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
