# Generated by Django 4.2.6 on 2025-04-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0047_fine_isconstructionzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='road_location',
            name='isConstructionZone',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
