# Generated by Django 4.2.6 on 2025-04-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0046_alter_quickpd_state_rs1'),
        ('video', '0048_alter_preodrxpressbillpay_state_rs1_and_more'),
    ]

    operations = [
    ]
