# Generated by Django 4.2.6 on 2025-04-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0046_duncansubmission_is_notfound_and_more'),
        ('video', '0048_road_location_isconstructionzone'),
    ]

    operations = [
    ]
