# Generated by Django 4.2.6 on 2025-04-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0049_merge_20250405_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
