# Generated by Django 4.2.6 on 2025-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0051_alter_quickpd_state_rs1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quickpd',
            name='state_rs5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
