# Generated by Django 4.2.6 on 2025-04-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0049_merge_20250408_1030'),
        ('video', '0052_alter_quickpd_state_rs2_alter_quickpd_state_rs3_and_more'),
    ]

    operations = [
    ]
