# Generated by Django 4.2.6 on 2025-04-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0053_merge_20250408_0024'),
        ('video', '0053_merge_20250408_1059'),
    ]

    operations = [
    ]
