# Generated by Django 4.2.6 on 2025-05-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0054_merge_20250408_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjudicationbin',
            old_name='is_adjudicated',
            new_name='is_adjudicated_in_adjudicationbin',
        ),
        migrations.RenameField(
            model_name='reviewbin',
            old_name='is_send_to_adj',
            new_name='is_adjudicated_in_review_bin',
        ),
        migrations.AddField(
            model_name='adjudicationbin',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='reviewbin',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewbin',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
# Generated by Django 4.2.6 on 2025-05-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0054_merge_20250408_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjudicationbin',
            old_name='is_adjudicated',
            new_name='is_adjudicated_in_adjudicationbin',
        ),
        migrations.RenameField(
            model_name='reviewbin',
            old_name='is_send_to_adj',
            new_name='is_adjudicated_in_review_bin',
        ),
        migrations.AddField(
            model_name='adjudicationbin',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='reviewbin',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewbin',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
