# Generated by Django 4.2.6 on 2025-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0055_rename_is_adjudicated_adjudicationbin_is_adjudicated_in_adjudicationbin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duncanmasterdata',
            name='is_address_updated',
            field=models.BooleanField(default=False, help_text='Previously marked as updated address in approved table'),
        ),
        migrations.AddField(
            model_name='duncanmasterdata',
            name='is_invalid_address',
            field=models.BooleanField(default=False, help_text='Previously marked as invalid in approved table'),
        ),
    ]
