# Generated by Django 4.2.6 on 2025-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0057_tattile_citation_citation_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattile',
            name='officer_badge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
