# Generated by Django 4.2.6 on 2025-06-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0058_alter_tattile_officer_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='citation_dissmissal_type',
            field=models.CharField(blank=True, choices=[('AD', 'AGENCY DECISION'), ('DUPC', 'DUPLICATE CITATION')], help_text='Type of citation dismissal if current_citation_status is DC', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='citationeditlog',
            name='citation_dissmissal_type',
            field=models.CharField(blank=True, choices=[('AD', 'AGENCY DECISION'), ('DUPC', 'DUPLICATE CITATION')], help_text='Type of citation dismissal if current_citation_status is X', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='citationswithupdatedaddress',
            name='old_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='citationswithupdatedaddress',
            name='updated_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sup_metadata',
            name='originalTimeApp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='current_citation_status',
            field=models.CharField(choices=[('OR', 'Original'), ('PIH', 'Paid In House'), ('RTS', 'Return To Sender, Unknown address'), ('UA', 'Updated Address'), ('TL', 'Transfer of Liability'), ('EF', 'Edit Fine'), ('CE', 'Citation Error'), ('X', 'Dismiss Citation')], default='OR', help_text='Current edit status flag', max_length=3),
        ),
        migrations.AlterField(
            model_name='citationeditlog',
            name='current_citation_status',
            field=models.CharField(choices=[('OR', 'Original'), ('PID', 'Paid In House'), ('RTS', 'Return To Sender'), ('UA', 'Updated Address'), ('TL', 'Transfer of Liability'), ('EF', 'Edit Fine'), ('CE', 'Citation Error'), ('X', 'Dismiss Citation')], default='OR', max_length=3),
        ),
        migrations.AlterField(
            model_name='citationeditlog',
            name='previous_citation_status',
            field=models.CharField(choices=[('OR', 'Original'), ('PID', 'Paid In House'), ('RTS', 'Return To Sender'), ('UA', 'Updated Address'), ('TL', 'Transfer of Liability'), ('EF', 'Edit Fine'), ('CE', 'Citation Error'), ('X', 'Dismiss Citation')], default='OR', max_length=3),
        ),
    ]
