# Generated by Django 4.2.6 on 2025-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0059_citation_citation_dissmissal_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odrcsvdata',
            old_name='incurred_date',
            new_name='line_item_incurred_date_1',
        ),
        migrations.RemoveField(
            model_name='odrcsvdata',
            name='line_item',
        ),
        migrations.RemoveField(
            model_name='odrcsvdata',
            name='line_item_amount',
        ),
        migrations.RemoveField(
            model_name='odrcsvdata',
            name='line_item_code',
        ),
        migrations.RemoveField(
            model_name='odrcsvdata',
            name='previous_fees_by_oca',
        ),
        migrations.AddField(
            model_name='odrcsvdata',
            name='fees_by_OCA_ECA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='odrcsvdata',
            name='line_item_amount_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='odrcsvdata',
            name='line_item_amount_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='odrcsvdata',
            name='line_item_code_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odrcsvdata',
            name='line_item_code_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odrcsvdata',
            name='line_item_incurred_date_2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
