# Generated by Django 4.2.6 on 2025-07-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0060_rename_incurred_date_odrcsvdata_line_item_incurred_date_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpaidcitation',
            name='odr_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
