# Generated by Django 4.2.6 on 2025-08-26 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0061_unpaidcitation_odr_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminFolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100)),
                ('parent_folder_id', models.IntegerField(blank=True, help_text='ID of the parent folder, if this is a subfolder', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_folders', to='video.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'super_admin_folders',
            },
        ),
        migrations.CreateModel(
            name='AgencyFileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=30)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_details', to='video.agency')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='video.superadminfolders')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agency_file_details',
            },
        ),
        migrations.AddConstraint(
            model_name='superadminfolders',
            constraint=models.UniqueConstraint(fields=('folder_name', 'agency'), name='unique_folder_per_agency'),
        ),
        migrations.AddConstraint(
            model_name='agencyfiledetails',
            constraint=models.UniqueConstraint(fields=('file_name', 'folder', 'agency'), name='unique_file_per_folder_agency'),
        ),
    ]
