# Generated by Django 4.2.6 on 2025-09-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0062_superadminfolders_agencyfiledetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyfiledetails',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
    ]
