# Generated by Django 4.2.6 on 2025-10-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0063_alter_agencyfiledetails_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='isRemainderSent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citation',
            name='remainderCombinedPdfPath',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='citation',
            name='remainderSentDate',
            field=models.DateTimeField(null=True),
        ),
    ]
