# Generated by Django 4.2.6 on 2025-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0064_citation_isremaindersent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
