# Generated by Django 5.2.8 on 2025-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0065_citation_fine_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sup_metadata',
            name='isMailCitationApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sup_metadata',
            name='isMailCitationRejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sup_metadata',
            name='mailCitationApprovedTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sup_metadata',
            name='mailCitationRejectedTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
