# Generated by Django 5.2.8 on 2026-01-06 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0066_sup_metadata_ismailcitationapproved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvidenceCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('evidence_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence_time', models.TimeField(default=django.utils.timezone.now)),
                ('evidence_speed', models.IntegerField(blank=True, null=True)),
                ('evidence_ID', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('badge_id', models.CharField(blank=True, max_length=100, null=True)),
                ('evidence_mapped_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_evidence_calibration_image', to='video.image')),
                ('tattile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_evidence_calibration_tattile', to='video.tattile')),
            ],
            options={
                'db_table': 'add_evidence_calibration',
            },
        ),
        migrations.CreateModel(
            name='EvidenceCalibrationBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_state', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.CharField(blank=True, max_length=100, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('camera_date', models.DateTimeField(blank=True, null=True)),
                ('camera_time', models.TimeField(blank=True, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_calibration_bin_image', to='video.image')),
                ('tattile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_calibration_bin_tattile', to='video.tattile')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_calibration_bin_video', to='video.video')),
            ],
            options={
                'db_table': 'evidence_calibration_bin',
            },
        ),
    ]
