# Generated by Django 5.2.9 on 2026-02-03 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0067_addevidencecalibration_evidencecalibrationbin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='current_citation_status',
            field=models.CharField(choices=[('OR', 'Original'), ('PIH', 'Paid In House'), ('RTS', 'Return To Sender, Unknown address'), ('UA', 'Updated Address'), ('TL', 'Transfer of Liability'), ('EF', 'Edit Fine'), ('CE', 'Citation Error'), ('X', 'Dismiss Citation'), ('WARN-A', 'Agency Warning')], default='OR', help_text='Current edit status flag', max_length=10),
        ),
        migrations.AlterField(
            model_name='citationeditlog',
            name='current_citation_status',
            field=models.CharField(choices=[('OR', 'Original'), ('PID', 'Paid In House'), ('RTS', 'Return To Sender'), ('UA', 'Updated Address'), ('TL', 'Transfer of Liability'), ('EF', 'Edit Fine'), ('CE', 'Citation Error'), ('X', 'Dismiss Citation'), ('WARN-A', 'Agency Warning')], default='OR', max_length=10),
        ),
        migrations.AlterField(
            model_name='citationeditlog',
            name='previous_citation_status',
            field=models.CharField(choices=[('OR', 'Original'), ('PID', 'Paid In House'), ('RTS', 'Return To Sender'), ('UA', 'Updated Address'), ('TL', 'Transfer of Liability'), ('EF', 'Edit Fine'), ('CE', 'Citation Error'), ('X', 'Dismiss Citation'), ('WARN-A', 'Agency Warning')], default='OR', max_length=10),
        ),
        migrations.CreateModel(
            name='CitationVersioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version_number', models.IntegerField(default=1)),
                ('versions', models.JSONField(default=list)),
                ('latest_status', models.CharField(default='OR', max_length=20)),
                ('latest_approved_date', models.DateTimeField(blank=True, null=True)),
                ('isAllowEdit', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citation_versioning', to='video.citation')),
            ],
            options={
                'db_table': 'citation_versioning',
            },
        ),
    ]
